"""Testing

Revision ID: 39c8ffee919a
Revises: b46ea99d2c5f
Create Date: 2024-05-25 23:32:45.309393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c8ffee919a'
down_revision: Union[str, None] = 'b46ea99d2c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('LoanEndDate', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('transaction', 'LoanDate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('LoanDate', sa.DATETIME(), nullable=True))
    op.drop_column('transaction', 'LoanEndDate')
    # ### end Alembic commands ###
