"""Modified transaction to add loans

Revision ID: e73d16676f2e
Revises: 
Create Date: 2024-05-25 21:30:01.970745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e73d16676f2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marble')
    op.drop_table('draft')
    op.drop_table('note')
    op.drop_table('user')
    op.drop_table('tournament_result')
    op.drop_table('rating')
    op.drop_table('transaction')
    op.drop_table('team')
    op.drop_table('big_tournament')
    op.drop_table('trade')
    op.drop_table('list')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('List_Num', sa.INTEGER(), nullable=True),
    sa.Column('Date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('trade',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('Date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('big_tournament',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('List_Num', sa.INTEGER(), nullable=True),
    sa.Column('Tournament_Num', sa.INTEGER(), nullable=True),
    sa.Column('Date', sa.DATETIME(), nullable=True),
    sa.Column('List_ID', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['List_ID'], ['list.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('team',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Ticker', sa.VARCHAR(length=1), nullable=True),
    sa.Column('Color', sa.VARCHAR(length=1), nullable=True),
    sa.Column('Money', sa.VARCHAR(length=1), nullable=True),
    sa.Column('Points', sa.VARCHAR(length=1), nullable=True),
    sa.Column('Slots', sa.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('Type', sa.VARCHAR(length=30), nullable=True),
    sa.Column('OriginalTeam', sa.VARCHAR(length=1), nullable=True),
    sa.Column('FinalTeam', sa.VARCHAR(length=1), nullable=True),
    sa.Column('Unsigned', sa.BOOLEAN(), nullable=True),
    sa.Column('Money_Cost', sa.INTEGER(), nullable=True),
    sa.Column('Points_Cost', sa.INTEGER(), nullable=True),
    sa.Column('Pick_Number', sa.INTEGER(), nullable=True),
    sa.Column('Roster_Slot', sa.BOOLEAN(), nullable=True),
    sa.Column('Date', sa.DATETIME(), nullable=True),
    sa.Column('Marble_ID', sa.INTEGER(), nullable=True),
    sa.Column('Trade_ID', sa.INTEGER(), nullable=True),
    sa.Column('Draft_ID', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['Draft_ID'], ['draft.ID'], ),
    sa.ForeignKeyConstraint(['Marble_ID'], ['marble.ID'], ),
    sa.ForeignKeyConstraint(['Trade_ID'], ['trade.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('rating',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('Team', sa.VARCHAR(length=1), nullable=True),
    sa.Column('Position', sa.INTEGER(), nullable=True),
    sa.Column('TotalRating', sa.INTEGER(), nullable=True),
    sa.Column('Marble_ID', sa.INTEGER(), nullable=True),
    sa.Column('List_ID', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['List_ID'], ['list.ID'], ),
    sa.ForeignKeyConstraint(['Marble_ID'], ['marble.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('tournament_result',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('Marble_ID', sa.INTEGER(), nullable=True),
    sa.Column('Tournament_ID', sa.INTEGER(), nullable=True),
    sa.Column('Team', sa.VARCHAR(length=1), nullable=True),
    sa.Column('Group', sa.VARCHAR(length=1), nullable=True),
    sa.Column('Group_Row', sa.INTEGER(), nullable=True),
    sa.Column('Race1', sa.INTEGER(), nullable=True),
    sa.Column('Race2', sa.INTEGER(), nullable=True),
    sa.Column('Race3', sa.INTEGER(), nullable=True),
    sa.Column('Race4', sa.INTEGER(), nullable=True),
    sa.Column('Group_Pos', sa.VARCHAR(length=1), nullable=True),
    sa.Column('OnevOne', sa.VARCHAR(length=1), nullable=True),
    sa.Column('Top12', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['Marble_ID'], ['marble.ID'], ),
    sa.ForeignKeyConstraint(['Tournament_ID'], ['big_tournament.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('Password', sa.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data', sa.VARCHAR(length=10000), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('Type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('FindersBonus', sa.BOOLEAN(), nullable=True),
    sa.Column('SnakeDraft', sa.BOOLEAN(), nullable=True),
    sa.Column('TeamROrder', sa.INTEGER(), nullable=True),
    sa.Column('TeamUOrder', sa.INTEGER(), nullable=True),
    sa.Column('TeamJOrder', sa.INTEGER(), nullable=True),
    sa.Column('TeamAOrder', sa.INTEGER(), nullable=True),
    sa.Column('TeamRPoints', sa.INTEGER(), nullable=True),
    sa.Column('TeamUPoints', sa.INTEGER(), nullable=True),
    sa.Column('TeamJPoints', sa.INTEGER(), nullable=True),
    sa.Column('TeamAPoints', sa.INTEGER(), nullable=True),
    sa.Column('Date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('marble',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('Team', sa.VARCHAR(length=1), nullable=True),
    sa.Column('Cheat', sa.BOOLEAN(), nullable=True),
    sa.Column('Weight', sa.INTEGER(), nullable=True),
    sa.Column('Diameter1', sa.INTEGER(), nullable=True),
    sa.Column('Diameter2', sa.INTEGER(), nullable=True),
    sa.Column('Image', sa.VARCHAR(length=50), nullable=True),
    sa.Column('Time_Trials', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Name')
    )
    # ### end Alembic commands ###
