"""Added Teams

Revision ID: fe85bc137c9f
Revises: 0d664585be12
Create Date: 2024-06-26 22:19:25.349522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe85bc137c9f'
down_revision: Union[str, None] = '0d664585be12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marble', sa.Column('TeamPosition', sa.Integer(), nullable=True))
    op.add_column('team', sa.Column('Ticker', sa.String(length=1), nullable=True))
    op.add_column('team', sa.Column('Slots', sa.Integer(), nullable=True))
    op.add_column('team', sa.Column('MascotSlots', sa.Integer(), nullable=True))
    op.add_column('team', sa.Column('Money', sa.Integer(), nullable=True))
    op.add_column('team', sa.Column('Points', sa.Integer(), nullable=True))
    op.add_column('team', sa.Column('ColorR', sa.Integer(), nullable=True))
    op.add_column('team', sa.Column('ColorG', sa.Integer(), nullable=True))
    op.add_column('team', sa.Column('ColorB', sa.Integer(), nullable=True))
    op.drop_column('team', 'List_Num')
    op.drop_column('team', 'Date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('Date', sa.DATETIME(), nullable=True))
    op.add_column('team', sa.Column('List_Num', sa.INTEGER(), nullable=True))
    op.drop_column('team', 'ColorB')
    op.drop_column('team', 'ColorG')
    op.drop_column('team', 'ColorR')
    op.drop_column('team', 'Points')
    op.drop_column('team', 'Money')
    op.drop_column('team', 'MascotSlots')
    op.drop_column('team', 'Slots')
    op.drop_column('team', 'Ticker')
    op.drop_column('marble', 'TeamPosition')
    # ### end Alembic commands ###
